## 현재 저장된 그래프 데이터 파악

In [234]:
import pickle
import pandas as pd
import torch

In [186]:
with open("data.pkl", 'rb') as f:
    dataset = pickle.load(f)

In [187]:
data_dict = {
        'graph': dataset['train-graph'],
        'val_matrix': None,
        'test_matrix': None,
        'item_texts': dataset['item-texts'],
        'testset': dataset['testset'],
        'user_ntype': dataset['user-type'],
        'item_ntype': dataset['item-type'],
        'user_to_item_etype': dataset['user-to-item-type'],
        'timestamp': dataset['timestamp-edge-column'],
        'user_category': dataset['user-category'],
        'item_category': dataset['item-category']
    }

In [188]:
data_dict['graph']

Graph(num_nodes={'user': 21, 'wine': 117},
      num_edges={('user', 'rated', 'wine'): 145, ('wine', 'rated-by', 'user'): 145},
      metagraph=[('user', 'wine', 'rated'), ('wine', 'user', 'rated-by')])

In [189]:
data_dict['user_category']

{3: 1371789,
 2: 1009837,
 6: 2138129,
 0: 73013,
 5: 2076035,
 4: 1739543,
 1: 183836,
 14: 9187145,
 13: 8882561,
 12: 4505281,
 9: 3774978,
 15: 10822212,
 17: 13191685,
 8: 3225781,
 10: 3912706,
 20: 26503486,
 7: 2365098,
 19: 19991573,
 16: 11933651,
 18: 18189324,
 11: 3934018}

In [190]:
g = data_dict['graph']
item_ntype = data_dict['item_ntype']
user_ntype = data_dict['user_ntype']
user_to_item_etype = data_dict['user_to_item_etype']
timestamp = data_dict['timestamp']

In [191]:
g

Graph(num_nodes={'user': 21, 'wine': 117},
      num_edges={('user', 'rated', 'wine'): 145, ('wine', 'rated-by', 'user'): 145},
      metagraph=[('user', 'wine', 'rated'), ('wine', 'user', 'rated-by')])

In [192]:
item_ntype

'wine'

In [193]:
user_ntype

'user'

In [194]:
user_to_item_etype

'rated'

In [195]:
timestamp

'timestamp'

In [226]:
nid_uid_dict = {v: k for v, k in enumerate(g.ndata['userID']['user'].numpy())}
nid_wid_dict = {v: k for v, k in  enumerate(g.ndata['wine_id']['wine'].numpy())}

In [228]:
g.ndata.keys()

dict_keys(['userID', 'user_feats', 'wine_id', 'grapes_id', 'wine_feats'])

In [229]:
g.ndata['wine_id']

{'wine': tensor([114, 103,  23,  75,  90,  72,  81,  39,  50,   2,  88,  82,  64,  36,
          37,  69,  79,  56,  44,  17,  12,  83,  71, 105,  31,  55,  78,  93,
          47,  99,  70,  35, 111,  40,   7,  38,  53,  67,  52,  95,  58,  18,
          54,  85,  15,  22, 102,  48, 108, 107, 106,  42,  89,   3, 100,  86,
          87,  41, 113, 115,  32,   9,  63,   4,  45,  91, 116, 109,  77,  60,
          84, 104, 112,  92,  49,  11,  94,  76,   8,  57, 101,   5,   6,  33,
          66,  14,  80,   1,  21,  97,  62,  74,  24,  96,  98,  34,  28,  30,
          19,  46,  25,   0,  20,  10,  27, 110,  43,  68,  73,  26,  61,  16,
          65,  29,  51,  59,  13])}

In [231]:
g.nodes['user']

NodeSpace(data={'userID': tensor([ 3,  2,  6,  0,  5,  4,  1, 14, 13, 12,  9, 15, 17,  8, 10, 20,  7, 19,
        16, 18, 11]), 'user_feats': tensor([[7.8000e+02, 3.9550e+03],
        [3.3780e+03, 4.1420e+03],
        [3.1500e+02, 3.1340e+03],
        [2.5840e+03, 3.0810e+03],
        [8.6200e+02, 3.7350e+03],
        [2.5630e+03, 2.6660e+03],
        [7.5900e+02, 2.7370e+03],
        [3.0600e+02, 2.3770e+03],
        [6.5500e+02, 1.9970e+03],
        [2.2000e+01, 3.3360e+03],
        [2.1700e+02, 1.9140e+03],
        [2.2400e+02, 1.7440e+03],
        [8.2900e+02, 1.3980e+03],
        [3.3900e+02, 1.1710e+03],
        [4.0700e+02, 1.0260e+03],
        [3.0000e+01, 7.2000e+02],
        [3.0000e+00, 3.3400e+02],
        [7.0000e+00, 2.7700e+02],
        [4.8000e+01, 2.8400e+02],
        [7.0000e+00, 2.6400e+02],
        [3.0000e+00, 2.7200e+02]])})

In [241]:
torch.arange(g.ndata['wine_id']['wine'].shape[0]).split(5)

(tensor([0, 1, 2, 3, 4]),
 tensor([5, 6, 7, 8, 9]),
 tensor([10, 11, 12, 13, 14]),
 tensor([15, 16, 17, 18, 19]),
 tensor([20, 21, 22, 23, 24]),
 tensor([25, 26, 27, 28, 29]),
 tensor([30, 31, 32, 33, 34]),
 tensor([35, 36, 37, 38, 39]),
 tensor([40, 41, 42, 43, 44]),
 tensor([45, 46, 47, 48, 49]),
 tensor([50, 51, 52, 53, 54]),
 tensor([55, 56, 57, 58, 59]),
 tensor([60, 61, 62, 63, 64]),
 tensor([65, 66, 67, 68, 69]),
 tensor([70, 71, 72, 73, 74]),
 tensor([75, 76, 77, 78, 79]),
 tensor([80, 81, 82, 83, 84]),
 tensor([85, 86, 87, 88, 89]),
 tensor([90, 91, 92, 93, 94]),
 tensor([95, 96, 97, 98, 99]),
 tensor([100, 101, 102, 103, 104]),
 tensor([105, 106, 107, 108, 109]),
 tensor([110, 111, 112, 113, 114]),
 tensor([115, 116]))

## 데이터 전처리 하는 부분..

In [21]:
import os

In [22]:
print('Processing Started!')
path = os.getcwd()

directory = os.path.join(path, "data")
directory

Processing Started!


'C:\\tech\\Study\\pin\\PinSAGE\\data'

In [ ]:
import json

In [23]:
# User Data
with open(os.path.join(directory, 'user.json')) as f:
    user_json = json.load(f)
users = pd.DataFrame(user_json["data"])
users

index    userID  user_follower_count  user_rating_count
0          0   5145589               5364.0            16610.0
1          1   2430463               3839.0            14920.0
2          2   2867095              22586.0            11441.0
3          3    248277               8856.0            12502.0
4          4  11195950               1738.0            11530.0
...      ...       ...                  ...                ...
52250  52250  26790761                  1.0                0.0
52251  52251  22784366                  1.0                1.0
52252  52252   4465516                  0.0                0.0
52253  52253  13591414                  0.0                1.0
52254  52254   4870982                  0.0                0.0

[52255 rows x 4 columns]

In [24]:
columns = ['userID', 'user_follower_count', 'user_rating_count']
users = users[columns]
users

userID  user_follower_count  user_rating_count
0       5145589               5364.0            16610.0
1       2430463               3839.0            14920.0
2       2867095              22586.0            11441.0
3        248277               8856.0            12502.0
4      11195950               1738.0            11530.0
...         ...                  ...                ...
52250  26790761                  1.0                0.0
52251  22784366                  1.0                1.0
52252   4465516                  0.0                0.0
52253  13591414                  0.0                1.0
52254   4870982                  0.0                0.0

[52255 rows x 3 columns]

In [25]:
users = users.dropna(subset=['userID'])
users['user_feats'] = list(users[['user_follower_count', 'user_rating_count']].values)
users

userID  user_follower_count  user_rating_count          user_feats
0       5145589               5364.0            16610.0   [5364.0, 16610.0]
1       2430463               3839.0            14920.0   [3839.0, 14920.0]
2       2867095              22586.0            11441.0  [22586.0, 11441.0]
3        248277               8856.0            12502.0   [8856.0, 12502.0]
4      11195950               1738.0            11530.0   [1738.0, 11530.0]
...         ...                  ...                ...                 ...
52250  26790761                  1.0                0.0          [1.0, 0.0]
52251  22784366                  1.0                1.0          [1.0, 1.0]
52252   4465516                  0.0                0.0          [0.0, 0.0]
52253  13591414                  0.0                1.0          [0.0, 1.0]
52254   4870982                  0.0                0.0          [0.0, 0.0]

[52255 rows x 4 columns]

In [26]:
# Wine Data
with open(os.path.join(directory, 'wine.json')) as f:
    item_json = json.load(f)
items = pd.DataFrame(item_json["data"])
items = items.dropna()
items

index  wine_id                               name  rating_average  \
0          0  1938520            1882 Cabernet Sauvignon             4.1   
1          1    14604             Les Bessards Hermitage             4.3   
2          2  1930757             Patriarch Estate Grown             4.6   
3          3  1564280                             Merlot             4.3   
4          4  2576427         Cabernet Sauvignon F Block             4.4   
...      ...      ...                                ...             ...   
50855  50855  1669561           Garganega - Pinot Grigio             3.5   
50856  50856  1861275             Dadà Langhe Chardonnay             3.8   
50857  50857  2201892     Metodo Zero Prosecco Extra Dry             3.9   
50858  50858  2396179          Les Monts Damnés Sancerre             4.2   
50859  50859  7715684  Gran Paso a Paso Doble Monastrell             4.1   

       body  acidity_x  alcohol  grapes_id  
0       5.0        2.0     14.5        [2]  
1       5.0        3.0     14.0        [1]  
2       4.0        3.0     14.2    [2, 10]  
3       4.0        3.0     14.4       [10]  
4       5.0        2.0      0.0        [2]  
...     ...        ...      ...        ...  
50855   3.0        3.0      0.0  [104, 34]  
50856   3.0        3.0     13.5        [5]  
50857   1.0        3.0      0.0      [112]  
50858   4.0        3.0     13.5       [17]  
50859   5.0        3.0      0.0       [88]  

[44023 rows x 8 columns]

In [27]:
columns = ['wine_id', 'name', 'rating_average', 'body', 'acidity_x', 'alcohol', 'grapes_id']
items = items[columns]
items = items.dropna(subset=['wine_id', 'grapes_id'])
items

wine_id                               name  rating_average  body  \
0      1938520            1882 Cabernet Sauvignon             4.1   5.0   
1        14604             Les Bessards Hermitage             4.3   5.0   
2      1930757             Patriarch Estate Grown             4.6   4.0   
3      1564280                             Merlot             4.3   4.0   
4      2576427         Cabernet Sauvignon F Block             4.4   5.0   
...        ...                                ...             ...   ...   
50855  1669561           Garganega - Pinot Grigio             3.5   3.0   
50856  1861275             Dadà Langhe Chardonnay             3.8   3.0   
50857  2201892     Metodo Zero Prosecco Extra Dry             3.9   1.0   
50858  2396179          Les Monts Damnés Sancerre             4.2   4.0   
50859  7715684  Gran Paso a Paso Doble Monastrell             4.1   5.0   

       acidity_x  alcohol  grapes_id  
0            2.0     14.5        [2]  
1            3.0     14.0        [1]  
2            3.0     14.2    [2, 10]  
3            3.0     14.4       [10]  
4            2.0      0.0        [2]  
...          ...      ...        ...  
50855        3.0      0.0  [104, 34]  
50856        3.0     13.5        [5]  
50857        3.0      0.0      [112]  
50858        3.0     13.5       [17]  
50859        3.0      0.0       [88]  

[44023 rows x 7 columns]

In [28]:
items['grapes_id'] = [i[1] for i in items['grapes_id']]
items['wine_feats'] = list(items[['rating_average', 'body', 'acidity_x', 'alcohol']].values)
items

wine_id                               name  rating_average  body  \
0      1938520            1882 Cabernet Sauvignon             4.1   5.0   
1        14604             Les Bessards Hermitage             4.3   5.0   
2      1930757             Patriarch Estate Grown             4.6   4.0   
3      1564280                             Merlot             4.3   4.0   
4      2576427         Cabernet Sauvignon F Block             4.4   5.0   
...        ...                                ...             ...   ...   
50855  1669561           Garganega - Pinot Grigio             3.5   3.0   
50856  1861275             Dadà Langhe Chardonnay             3.8   3.0   
50857  2201892     Metodo Zero Prosecco Extra Dry             3.9   1.0   
50858  2396179          Les Monts Damnés Sancerre             4.2   4.0   
50859  7715684  Gran Paso a Paso Doble Monastrell             4.1   5.0   

       acidity_x  alcohol grapes_id             wine_feats  
0            2.0     14.5         2  [4.1, 5.0, 2.0, 14.5]  
1            3.0     14.0         1  [4.3, 5.0, 3.0, 14.0]  
2            3.0     14.2         2  [4.6, 4.0, 3.0, 14.2]  
3            3.0     14.4         1  [4.3, 4.0, 3.0, 14.4]  
4            2.0      0.0         2   [4.4, 5.0, 2.0, 0.0]  
...          ...      ...       ...                    ...  
50855        3.0      0.0         1   [3.5, 3.0, 3.0, 0.0]  
50856        3.0     13.5         5  [3.8, 3.0, 3.0, 13.5]  
50857        3.0      0.0         1   [3.9, 1.0, 3.0, 0.0]  
50858        3.0     13.5         1  [4.2, 4.0, 3.0, 13.5]  
50859        3.0      0.0         8   [4.1, 5.0, 3.0, 0.0]  

[44023 rows x 8 columns]

In [29]:
# Rating Data
# 8:2
columns = ['userID', 'wine_id', 'rating_per_user']

with open(os.path.join(directory, 'train.json')) as f:
    train = json.load(f)
train.keys()

dict_keys(['schema', 'data'])

In [30]:
train = pd.DataFrame(train['data'])
train

index    userID  wine_id  rating_per_user
0      633370   3201769    89202              3.0
1      710514    602552  1145046              1.0
2      249331    527081     1264              4.0
3      166164  10465117  1142030              4.0
4      271885  35392086  1231186              3.5
...       ...       ...      ...              ...
79995  146673   1434808  1984784              4.0
79996  609310  14695535  1265906              4.0
79997  269580    787767  1244403              3.5
79998  114850  11335597  1126888              3.5
79999  742364   3774689  1164751              2.0

[80000 rows x 4 columns]

In [31]:
'''
* Like
I thought about whether it would be a good choice to recommend an item that the user did not evaluate well.
If you want to learn regardless of the rating, you can remove the code related to like.

We set the standard for like as a rating of 3.
I think it would be good to set this part according to your own thoughts.
'''
train['like'] = [1 if x >= 3 else 0 for x in train['rating_per_user']]
train = train[train['like'] == 1]
train

index    userID  wine_id  rating_per_user  like
0      633370   3201769    89202              3.0     1
2      249331    527081     1264              4.0     1
3      166164  10465117  1142030              4.0     1
4      271885  35392086  1231186              3.5     1
5      318987    811680  1100962              3.0     1
...       ...       ...      ...              ...   ...
79994  207296  25893258  1254221              3.5     1
79995  146673   1434808  1984784              4.0     1
79996  609310  14695535  1265906              4.0     1
79997  269580    787767  1244403              3.5     1
79998  114850  11335597  1126888              3.5     1

[76644 rows x 5 columns]

In [32]:
train = train[columns]
train

userID  wine_id  rating_per_user
0       3201769    89202              3.0
2        527081     1264              4.0
3      10465117  1142030              4.0
4      35392086  1231186              3.5
5        811680  1100962              3.0
...         ...      ...              ...
79994  25893258  1254221              3.5
79995   1434808  1984784              4.0
79996  14695535  1265906              4.0
79997    787767  1244403              3.5
79998  11335597  1126888              3.5

[76644 rows x 3 columns]

In [33]:
with open(os.path.join(directory, 'test.json')) as f:
    test = json.load(f)
test = pd.DataFrame(test['data'])

test['like'] = [1 if x >= 3 else 0 for x in test['rating_per_user']]
test = test[test['like'] == 1]
test = test[columns]
test

userID  wine_id  rating_per_user
0       4694874  2050654              3.5
1      29548898  2099476              4.0
2       8995027    84700              4.0
3       1614172    16778              4.5
4        825579  1136013              3.5
...         ...      ...              ...
19995   9856812     7073              5.0
19996  22632827  1126473              3.5
19997   3628838  1211301              4.0
19998  39185091  1136139              3.5
19999  27584076    19279              4.5

[19131 rows x 3 columns]

In [34]:
ratings = pd.concat([train, test], axis=0, ignore_index=True)
user_filter = [k for k, v in ratings['userID'].value_counts().items() if v > 1]
ratings = ratings[ratings['userID'].isin(user_filter)]

In [35]:
ratings

userID  wine_id  rating_per_user
0       3201769    89202              3.0
1        527081     1264              4.0
2      10465117  1142030              4.0
3      35392086  1231186              3.5
4        811680  1100962              3.0
...         ...      ...              ...
95770   9856812     7073              5.0
95771  22632827  1126473              3.5
95772   3628838  1211301              4.0
95773  39185091  1136139              3.5
95774  27584076    19279              4.5

[95046 rows x 3 columns]

In [115]:
m = (ratings['userID'].value_counts() == 7)

In [116]:
ratings['userID'].value_counts()[m]

183836      7
8882561     7
3225781     7
3912706     7
13191685    7
18189324    7
3934018     7
1009837     7
2076035     7
73013       7
4505281     7
2365098     7
26503486    7
10822212    7
2138129     7
9187145     7
1371789     7
19991573    7
11933651    7
1739543     7
3774978     7
Name: userID, dtype: int64